import random


RANDOM_USERNAMES = (
    'StarryNavigator', 
    'PixelPanda',
    'EchoMeadow',
    'QuantumQuokka',
    'MysticMariner',
    'NebulaNoodle',
    'FrostFox',
    'SolarSparrow',
    'GalacticGazelle',
    'LunarLynx',
    'CosmicChameleon',
    'AstroAardvark',
    'TwilightToucan',
    'ZenZebra',
    'RadiantRaccoon',
    'EmberElephant',
    'BreezyBadger',
    'AuroraAlpaca',
    'DazzleDolphin',
    'WhisperingWillow',
    'SapphireSphinx',
    'VelvetVulture',
    'CrimsonCobra',
    'AmberAntelope',
    'GlitterGiraffe',
    'ThunderTiger',
    'MirageMeerkat',
    'OasisOcelot',
    'PhantomPhoenix',
    'MirageMongoose',
    'EnigmaEagle',
    'BlazeBear',
    'InfinityIbex',
    'DreamyDragonfly',
    'MirageMarmoset',
    'MysticMoose',
    'SolarSeahorse',
    'CelestialCheetah',
    'WhisperWolf',
    'ZenithZebra',
    'PulsarParrot',
    'OpalOtter',
    'GlimmerGriffin',
    'TerraToucan',
    'LunarLemur',
    'NovaNightingale',
    'SereneSwan',
    'EclipseEel',
    'BorealBadger',
    'CelestialCrane'
)


def get_random_name():
    return random.choice(RANDOM_USERNAMES) + str(random.randint(10, 99))
